import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import s from "styles/home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>meta-pass</title>
        <meta name="description" content="Generated by meta-pass" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.bannerPage}>
        <div className={s.centerContent}>
          <div className={s.logoWrapper}>
            <Image fill src="/images/logoForBanner.svg" alt="sky-banner" />
          </div>
          <div className={s.cube}>
            <Image fill src="/images/cube.png" alt="sky-banner" />
          </div>
          <button type="button" className={s.button} disabled>
            Play
          </button>
        </div>
        <div className={s.footer}>
          <Link href="/" className={s.link}>
            Terms of use
          </Link>
          <Link href="/" className={s.link}>
            Сookie policy
          </Link>
          <Link href="/" className={s.link}>
            Privacy policy
          </Link>
        </div>
        <div className={s.background}>
          <Image fill
            src="/images/skyBanner.jpg"
            style={{ objectFit: "cover" }}
            alt="sky-banner"
          />
        </div>
      </div>
    </>
  );
}
